# version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking_api_dev

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking_api_dev"]
      interval: 30s
      timeout: 10s
      retries: 5

  bankingapp-api:
    image: bankingapi
    pull_policy: build

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_CLOUD_CONFIG_ENABLED: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_api_dev
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: startmeup

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s

    ports:
      - "8080:8080"

    volumes:
      - /data/compose-app:/data/compose-app

networks:
  default:
    external: true
    name: niitnetwork

volumes:
  pgdata: